/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Post;

import Vistas.Post.PublicacionesEstudiante;
import Aplicacion.Control;
import DTOs.EstudianteDTO;
import DTOs.PostDTO;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class PanelPublicaciones extends javax.swing.JPanel {
private Control control;

private EstudianteDTO estudiante;

    /**
     * Creates new form PanelPublicaciones
     */
    public PanelPublicaciones(Control control) {
        this.control = control;
        this.estudiante = control.getEstudiante();
        initComponents();
        cargarFeed();
        scrollFeed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFeed = new javax.swing.JScrollPane();
        barra = new javax.swing.JScrollBar();
        panelContenido = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(604, 508));
        setMinimumSize(new java.awt.Dimension(604, 508));
        setPreferredSize(new java.awt.Dimension(604, 508));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFeed.setMaximumSize(new java.awt.Dimension(580, 420));
        panelFeed.setMinimumSize(new java.awt.Dimension(580, 420));
        panelFeed.setPreferredSize(new java.awt.Dimension(580, 440));
        panelFeed.setViewportView(barra);

        add(panelFeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 580, 420));

        panelContenido.setMaximumSize(new java.awt.Dimension(548, 440));
        panelContenido.setMinimumSize(new java.awt.Dimension(548, 440));
        panelContenido.setPreferredSize(new java.awt.Dimension(548, 440));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 410));

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarPerfil();
    }//GEN-LAST:event_btnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar barra;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JScrollPane panelFeed;
    // End of variables declaration//GEN-END:variables

public void scrollFeed(){
        panelFeed.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        panelFeed.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        barra = panelFeed.getVerticalScrollBar();        
        panelFeed.addMouseWheelListener((new MouseWheelListener() {
        private boolean scroll = false;
   
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                e.consume();
                if(scroll || panelContenido.getComponentCount() == 0)return;
                scroll = true;
                
                panelContenido.revalidate();
                Component post1 =  panelContenido.getComponent(0);
                int alturaPost = post1.getPreferredSize().height +10;
                int direccion = e.getWheelRotation();
                int posicionActual = barra.getValue();
                int posicionDeseada = posicionActual + direccion* alturaPost;
 
                final int nuevaPosicion = Math.max(0, Math.min(posicionDeseada, barra.getMaximum() - barra.getVisibleAmount()));
                Timer timer = new Timer(5, null);
                timer.addActionListener(ae ->{
                    int valorA = barra.getValue();
                    int velocidad = 10;
                    if(direccion> 0){
                        int siguiente = Math.min(valorA + velocidad, nuevaPosicion);
                        barra.setValue(siguiente);
                        if(siguiente >= nuevaPosicion)
                        {
                            timer.stop();
                            scroll = false;
                        }
                    }else{
                        int siguiente = Math.max(valorA- velocidad, nuevaPosicion);
                        barra.setValue(siguiente);
                        if(siguiente<= nuevaPosicion) {
                            timer.stop();
                            scroll = false;
                        }
                    }
                });
                timer.start();
             }
         }));  
     }

 public void cargarFeed(){
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
        panelContenido.removeAll();
        panelContenido.setPreferredSize(new Dimension(548, control.cargarPostEstudiante(this.estudiante).size()*(440+10)));
        for(PostDTO post: control.cargarPostEstudiante(this.estudiante)){
            System.out.println(post.toString());
            PublicacionesEstudiante publicacion = new PublicacionesEstudiante(control, post);   

            panelContenido.add(publicacion);         
            panelContenido.add(Box.createVerticalStrut(10));
        }
            panelContenido.revalidate();
            panelContenido.repaint();
            panelFeed.setViewportView(panelContenido);
            panelFeed.revalidate();
            panelFeed.repaint();
    }
}