/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;
import DTOs.EstudianteDTO;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.util.regex.Pattern;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sandra
 */
public class BuscarEstudiante extends javax.swing.JPanel {
private Control control;
    /**
     * Creates new form Explorar
     */
    public BuscarEstudiante(Control control) {
        this.control = control;
        initComponents();
        valoresDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnPerfil = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(515, 567));
        setMinimumSize(new java.awt.Dimension(515, 539));
        setPreferredSize(new java.awt.Dimension(515, 567));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(campoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 440, 40));

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Resultados Busqueda"
            }
        ));
        tablaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEstudiantes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 480, 410));

        btnPerfil.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\miperfil.png")); // NOI18N
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 40, -1));

        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\hogar.png")); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 40, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\vaso.png")); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 40, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Busqueda de estudiantes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        control.mostrarBuscarEstudiante();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:
        control.mostrarPerfil();
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void tablaEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudiantesMouseClicked
        // TODO add your handling code here:
        seleccionarEstudiante();
       control.mostrarPerfilEstudiante();
    }//GEN-LAST:event_tablaEstudiantesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables

    
    
    public void seleccionarEstudiante(){
        int filaSeleccionada = tablaEstudiantes.getSelectedRow();
        if(filaSeleccionada != -1){
            int modelRow = tablaEstudiantes.convertRowIndexToModel(filaSeleccionada);
            EstudianteDTO estudianteSeleccionado = control.cargarEstudiantesPorNombre(campoBuscar.getText()).get(modelRow);
            System.out.println("Estudiante seleccionado:  " + estudianteSeleccionado.toString());
            control.setEstudianteBuscado(estudianteSeleccionado);
            
        }
        
        
    }
    public void CargarTabla(){
            campoBuscar.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Nombre Estudiante"}, 0
            ) {
            @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
        model.setRowCount(0);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);

        tablaEstudiantes.setRowSorter(sorter);
        for (EstudianteDTO estudiante : control.cargarEstudiantesPorNombre(campoBuscar.getText())) {
            String nombreC = estudiante.getNombre() + " " +estudiante.getApellidoPaterno() + " " +estudiante.getApellidoMaterno();

            model.addRow(new Object[]{nombreC});
        }
        tablaEstudiantes.setModel(model);
        tablaEstudiantes.setRowSelectionAllowed(true);
        tablaEstudiantes.setColumnSelectionAllowed(false);
        tablaEstudiantes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaEstudiantes.getTableHeader().setReorderingAllowed(false);
        tablaEstudiantes.getTableHeader().setResizingAllowed(false);
        
        tablaEstudiantes.setSelectionBackground(Color.CYAN);
        tablaEstudiantes.setSelectionForeground(Color.BLACK);
        
    }
    
    public void filtrarPorNombre() {
        String texto = campoBuscar.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tablaEstudiantes.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tablaEstudiantes.setRowSorter(sorter);
        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*" + Pattern.quote(texto) + ".*", 0));
         }
}
    public void valoresDefault(){
        CargarTabla();
        campoBuscar.getDocument().addDocumentListener(new DocumentListener() {
        @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorNombre();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorNombre();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrarPorNombre();
            }
        });
    }
}
