/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;
import DTOs.PostDTO;
import java.time.Instant;

/**
 *
 * @author HP
 */
public class CrearPost extends javax.swing.JPanel {
private Control control;
private PostDTO postCreado;
    /**
     * Creates new form CrearPost
     */
    public CrearPost(Control control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoMensaje = new javax.swing.JTextField();
        btnPublicar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(540, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(campoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 487, 330));

        btnPublicar.setBackground(new java.awt.Color(0, 0, 0));
        btnPublicar.setForeground(new java.awt.Color(255, 255, 255));
        btnPublicar.setText("Publicar");
        btnPublicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPublicarMouseClicked(evt);
            }
        });
        add(btnPublicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 100, 30));

        btnDescartar.setText("Descartar");
        btnDescartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescartarMouseClicked(evt);
            }
        });
        add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Crear Publicacion");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPublicarMouseClicked
        // TODO add your handling code here:
        crearPost();
        control.publicarPost(postCreado);
        control.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnPublicarMouseClicked

    private void btnDescartarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescartarMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnDescartarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnPublicar;
    private javax.swing.JTextField campoMensaje;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


    public void crearPost(){
        postCreado = new  PostDTO();
        postCreado.setMensaje(campoMensaje.getText());
        postCreado.setCreadoEn(Instant.now());
        postCreado.setEstudiante(control.getEstudiante());
       
        System.out.println("Estudiante que llega a CrearPost: Presentacion:  " + control.getEstudiante().toString());
        System.out.println("Post creado : " + postCreado.toString());
        
    }
}
