/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Vistas.Post.PanelPost;
import Aplicacion.Control;
import DTOs.PostDTO;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class FeedPrincipal extends javax.swing.JPanel {
private Control control;
    /**
     * Creates new form FeedPrincipal
     */
    public FeedPrincipal(Control control) {
        this.control = control;
       
        initComponents();
        cargarFeed();
        scrollFeed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        btnMensajes = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        panelFeed = new javax.swing.JScrollPane();
        barra = new javax.swing.JScrollBar();
        panelContenido = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(660, 541));
        setMinimumSize(new java.awt.Dimension(660, 541));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(660, 541));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        btnMensajes.setText("Mensajes");
        add(btnMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        btnPerfil.setText("Mi perifl");
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        panelFeed.setMaximumSize(new java.awt.Dimension(550, 440));
        panelFeed.setMinimumSize(new java.awt.Dimension(550, 440));
        panelFeed.setPreferredSize(new java.awt.Dimension(550, 440));

        barra.setMaximumSize(new java.awt.Dimension(580, 100));
        barra.setPreferredSize(new java.awt.Dimension(580, 420));
        panelFeed.setViewportView(barra);

        add(panelFeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 440));

        panelContenido.setMaximumSize(new java.awt.Dimension(550, 4000));
        panelContenido.setMinimumSize(new java.awt.Dimension(550, 440));
        panelContenido.setPreferredSize(new java.awt.Dimension(550, 440));
        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));
        add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 480, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:
        control.mostrarPerfil();
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        cargarFeed();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        control.mostrarBuscarEstudiante();
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar barra;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMensajes;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JScrollPane panelFeed;
    // End of variables declaration//GEN-END:variables

    public void cargarFeed(){
        
        panelContenido.removeAll();
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
        List<PostDTO> posts = control.cargarPostFeed();
        panelContenido.setPreferredSize(new Dimension(600, posts.size() * (440 + 10)));

        for (PostDTO post : posts) {
            boolean likeado = control.verificarLikeEstudiante(post);
            PanelPost publicacion = new PanelPost(control, post, likeado);
            panelContenido.add(publicacion);
            panelContenido.add(Box.createVerticalStrut(10));
        }
            panelContenido.revalidate();
            panelContenido.repaint();
            panelFeed.setViewportView(panelContenido);
            panelFeed.revalidate();
            panelFeed.repaint();
    }
 
  public void scrollFeed(){
        panelFeed.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        panelFeed.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        barra = panelFeed.getVerticalScrollBar();        
        panelFeed.addMouseWheelListener((new MouseWheelListener() {
        private boolean scroll = false;

            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                e.consume();
                if(scroll || panelContenido.getComponentCount() == 0)return;
                scroll = true;
                
                panelContenido.revalidate();
                Component post1 =  panelContenido.getComponent(0);
                int alturaPost = post1.getPreferredSize().height +10;
                int direccion = e.getWheelRotation();
                int posicionActual = barra.getValue();
                int posicionDeseada = posicionActual + direccion* alturaPost;
 
                final int nuevaPosicion = Math.max(0, Math.min(posicionDeseada, barra.getMaximum() - barra.getVisibleAmount()));
                Timer timer = new Timer(5, null);
                timer.addActionListener(ae ->{
                    int valorA = barra.getValue();
                    int velocidad = 10;
                    if(direccion> 0){
                        int siguiente = Math.min(valorA + velocidad, nuevaPosicion);
                        barra.setValue(siguiente);
                        if(siguiente >= nuevaPosicion)
                        {
                            timer.stop();
                            scroll = false;
                        }
                    }else{
                        int siguiente = Math.max(valorA- velocidad, nuevaPosicion);
                        barra.setValue(siguiente);
                        if(siguiente<= nuevaPosicion) {
                            timer.stop();
                            scroll = false;
                        }
                    }
                });
                timer.start();
             }
         }));  
     }
  

}
