/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;

/**
 *
 * @author HP
 */
public class menuPrincipal extends javax.swing.JPanel {
private Control control;
    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal(Control control) {
        this.control = control;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPerfil = new javax.swing.JButton();
        BtnMensajes = new javax.swing.JButton();
        panelPost = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(668, 530));
        setMinimumSize(new java.awt.Dimension(668, 530));
        setPreferredSize(new java.awt.Dimension(668, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPerfil.setText("mi perfil");
        BtnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPerfilMouseClicked(evt);
            }
        });
        add(BtnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        BtnMensajes.setText("mensajes");
        add(BtnMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        panelPost.setLayout(new java.awt.CardLayout());
        add(panelPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 450));

        BtnHome.setText("home");
        add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPerfilMouseClicked
        // TODO add your handling code here:
        control.MostrarPerfil();
    }//GEN-LAST:event_BtnPerfilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnMensajes;
    private javax.swing.JButton BtnPerfil;
    private javax.swing.JPanel panelPost;
    // End of variables declaration//GEN-END:variables
}
