/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;

/**
 *
 * @author HP
 */
public class menuPrincipal extends javax.swing.JPanel {
private Control control;
    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal(Control control) {
        this.control = control;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPerfil = new javax.swing.JButton();
        btnMensajes = new javax.swing.JButton();
        panelPost = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(668, 530));
        setMinimumSize(new java.awt.Dimension(668, 530));
        setPreferredSize(new java.awt.Dimension(668, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setText("mi perfil");
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        btnMensajes.setText("mensajes");
        add(btnMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        panelPost.setLayout(new java.awt.CardLayout());
        add(panelPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 450));

        btnHome.setText("home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        btnBuscar.setText("buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:
        control.MostrarPerfil();
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMensajes;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JPanel panelPost;
    // End of variables declaration//GEN-END:variables
}
