/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author HP
 */
public class PanelRegistroDatosPersonales extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroDatosPersonales
     */
    public PanelRegistroDatosPersonales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoConfirmarContrasenhia = new javax.swing.JTextField();
        campoContrasenhia = new javax.swing.JTextField();
        campoCorreoE = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnContiuar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(520, 650));
        setMinimumSize(new java.awt.Dimension(520, 650));
        setPreferredSize(new java.awt.Dimension(520, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Confirmar contrasenhia:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre(s):");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 127, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Apellido(s):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Correo electronico:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Contrasenhia:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 330, 40));

        campoConfirmarContrasenhia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoConfirmarContrasenhia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 330, 40));

        campoContrasenhia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoContrasenhia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 330, 40));

        campoCorreoE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoCorreoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 330, 40));

        campoApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 330, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Registro");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 90, 50));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 150, 40));

        BtnContiuar.setBackground(new java.awt.Color(0, 0, 0));
        BtnContiuar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnContiuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContiuar.setText("Continuar");
        BtnContiuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContiuarMouseClicked(evt);
            }
        });
        add(BtnContiuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnContiuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContiuarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnContiuarMouseClicked

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnContiuar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoConfirmarContrasenhia;
    private javax.swing.JTextField campoContrasenhia;
    private javax.swing.JTextField campoCorreoE;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
