/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author HP
 */
public class PanelRegistroInfoGeneral extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroInfoGeneral
     */
    public PanelRegistroInfoGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCancelar = new javax.swing.JButton();
        BtnContiuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoPasatiempos = new javax.swing.JTextField();
        campoHobbies = new javax.swing.JTextField();
        campoSemestre = new javax.swing.JTextField();
        campoCarrera = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 150, 40));

        BtnContiuar.setBackground(new java.awt.Color(0, 0, 0));
        BtnContiuar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnContiuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContiuar.setText("Confirmar");
        BtnContiuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContiuarMouseClicked(evt);
            }
        });
        add(BtnContiuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 150, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Pasatiempos:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Carrera:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Semestre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("hobbies:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        campoPasatiempos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoPasatiempos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 390, 80));

        campoHobbies.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoHobbies, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 390, 70));

        campoSemestre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 330, 40));

        campoCarrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 330, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Registro");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 90, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarMouseClicked

    private void BtnContiuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContiuarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnContiuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnContiuar;
    private javax.swing.JTextField campoCarrera;
    private javax.swing.JTextField campoHobbies;
    private javax.swing.JTextField campoPasatiempos;
    private javax.swing.JTextField campoSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
