/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;
import DTOs.PostDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author HP
 */
public class PanelPost extends javax.swing.JPanel {
private Control control;
private PostDTO postActual;
    /**
     * Creates new form PanelPost
     */
    public PanelPost(Control control, PostDTO post) {
        this.control = control;
        this.postActual = post;
        setPreferredSize(new Dimension(540, 450));
        initComponents();
        cargarPost();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMensaje = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        btnMeGusta = new javax.swing.JButton();
        labelCreadoEn = new javax.swing.JLabel();
        labelReacciones = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(540, 450));
        setMinimumSize(new java.awt.Dimension(540, 450));
        setPreferredSize(new java.awt.Dimension(540, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMensaje.setText("texto post");
        add(labelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 60, 490, 320));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelUsuario.setText("nombre usuario");
        add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnMeGusta.setText("me gusta");
        btnMeGusta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMeGustaMouseClicked(evt);
            }
        });
        add(btnMeGusta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        labelCreadoEn.setText("hora creacion");
        add(labelCreadoEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 120, -1));

        labelReacciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelReacciones.setText("0");
        add(labelReacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 50, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeGustaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeGustaMouseClicked
        // TODO add your handling code here:
        if(postActual.isLikeado()){
            btnMeGusta.setBackground(Color.red);
            postActual.setNumeroReacciones(postActual.getNumeroReacciones() + 1);
            postActual.setLikeado(true);
        }else{
           btnMeGusta.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_btnMeGustaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMeGusta;
    private javax.swing.JLabel labelCreadoEn;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelReacciones;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables

    public void cargarPost(){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")
                                                       .withZone(ZoneId.systemDefault());
        String fechaFormateada = formatter.format(postActual.getCreadoEn());
        labelMensaje.setText(postActual.getMensaje());
        labelCreadoEn.setText(fechaFormateada);
        labelUsuario.setText(postActual.getEstudiante().getNombre());
        labelReacciones.setText(postActual.getNumeroReacciones()+ "");
        
    }
}
