/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;
import DTOs.EstudianteDTO;

/**
 *
 * @author HP
 */
public class PanelRegistroDatosPersonales extends javax.swing.JPanel {
private Control control;
private EstudianteDTO estudianteaRegistrar;
    /**
     * Creates new form PanelRegistroDatosPersonales
     */
    public PanelRegistroDatosPersonales(Control control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoConfirmarContrasenhia = new javax.swing.JTextField();
        campoContrasenhia = new javax.swing.JTextField();
        campoCorreoE = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnContiuar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        campoApellidoM = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(520, 650));
        setMinimumSize(new java.awt.Dimension(520, 650));
        setPreferredSize(new java.awt.Dimension(520, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Confirmar contrasenhia:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre(s):");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Apellido Paterno:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Correo electronico:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Contrasenhia:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 330, 40));

        campoConfirmarContrasenhia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoConfirmarContrasenhia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 330, 40));

        campoContrasenhia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoContrasenhia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 330, 40));

        campoCorreoE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoCorreoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 330, 40));

        campoApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Registro");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, 50));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\perfil-del-usuario.png")); // NOI18N
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 90, 50));

        BtnContiuar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnContiuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContiuar.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\continuar.png")); // NOI18N
        BtnContiuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContiuarMouseClicked(evt);
            }
        });
        add(BtnContiuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 80, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Apellido Materno:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        campoApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(campoApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 330, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnContiuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContiuarMouseClicked
        // TODO add your handling code here:
        
        if(campoContrasenhia.getText().equals(campoConfirmarContrasenhia.getText())){
            crearEstudiante();
            control.setEstudiante(estudianteaRegistrar);
            control.mostrarRegistroInfoGeneral();
        }
    }//GEN-LAST:event_BtnContiuarMouseClicked

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarLogIn();
    }//GEN-LAST:event_BtnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnContiuar;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoConfirmarContrasenhia;
    private javax.swing.JTextField campoContrasenhia;
    private javax.swing.JTextField campoCorreoE;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    public void crearEstudiante(){
        estudianteaRegistrar = new EstudianteDTO();
        estudianteaRegistrar.setCorreo(campoCorreoE.getText());
        estudianteaRegistrar.setContrasenia(campoContrasenhia.getText());
        estudianteaRegistrar.setNombre(campoNombre.getText());
        estudianteaRegistrar.setApellidoPaterno(campoApellidoP.getText());
        estudianteaRegistrar.setApellidoMaterno(campoApellidoM.getText());
    }




}
