/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;
import DTOs.EstudianteDTO;
import static java.awt.SystemColor.control;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author HP
 */
public class PanelEditarPerfil extends javax.swing.JPanel {
private Control control;
private EstudianteDTO estudiante;
private List<String> listaHobbys;
    /**
     * Creates new form PanelEditarPerfil
     */
    public PanelEditarPerfil(Control control) {
        this.control = control;
        initComponents();
        iniciarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreUsuario = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellidoP = new javax.swing.JLabel();
        labelApellidoM = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();
        labelHobbys = new javax.swing.JLabel();
        campoCarrera = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        BtnConfirmar = new javax.swing.JButton();
        panelBoxes = new javax.swing.JPanel();
        boxMusica = new javax.swing.JCheckBox();
        boxPeliculas = new javax.swing.JCheckBox();
        boxFototgrafia = new javax.swing.JCheckBox();
        boxViajes = new javax.swing.JCheckBox();
        boxTecnologia = new javax.swing.JCheckBox();
        boxCocina = new javax.swing.JCheckBox();
        boxBaile = new javax.swing.JCheckBox();
        boxLibros = new javax.swing.JCheckBox();
        boxDeportes = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(686, 521));
        setMinimumSize(new java.awt.Dimension(686, 521));
        setPreferredSize(new java.awt.Dimension(686, 521));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombreUsuario.setText("NombreUsuario");
        add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelNombre.setText("Nombre");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        labelApellidoP.setText("Apellido Paterno");
        add(labelApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        labelApellidoM.setText("Apellido Materno");
        add(labelApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labelCorreo.setText("Correo");
        add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        labelCarrera.setText("Carrera");
        add(labelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        labelHobbys.setText("Hobbys");
        add(labelHobbys, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        add(campoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 220, 30));
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 230, 30));
        add(campoApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 30));
        add(campoApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 220, 30));
        add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 220, 30));

        BtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 100, 40));

        panelBoxes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxMusica.setText("MUSICA");
        panelBoxes.add(boxMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        boxPeliculas.setText("PELICULAS");
        panelBoxes.add(boxPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        boxFototgrafia.setText("FOTOGRAFIA");
        panelBoxes.add(boxFototgrafia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        boxViajes.setText("VIAJES");
        panelBoxes.add(boxViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        boxTecnologia.setText("TECNOLOGIA");
        panelBoxes.add(boxTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        boxCocina.setText("COCINA");
        panelBoxes.add(boxCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        boxBaile.setText("BAILE");
        panelBoxes.add(boxBaile, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        boxLibros.setText("LIBROS");
        panelBoxes.add(boxLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        boxDeportes.setText("DEPORTES");
        panelBoxes.add(boxDeportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        add(panelBoxes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 320, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
        obtenerDatos();
        control.mostrarPerfil();
        //logica para confirmar los cambios en el usuario, falta armar DTO

    }//GEN-LAST:event_BtnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JCheckBox boxBaile;
    private javax.swing.JCheckBox boxCocina;
    private javax.swing.JCheckBox boxDeportes;
    private javax.swing.JCheckBox boxFototgrafia;
    private javax.swing.JCheckBox boxLibros;
    private javax.swing.JCheckBox boxMusica;
    private javax.swing.JCheckBox boxPeliculas;
    private javax.swing.JCheckBox boxTecnologia;
    private javax.swing.JCheckBox boxViajes;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoCarrera;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel labelApellidoM;
    private javax.swing.JLabel labelApellidoP;
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelHobbys;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JPanel panelBoxes;
    // End of variables declaration//GEN-END:variables


    public void iniciarPanel(){
        this.estudiante = control.getEstudiante();
        cargarDatos();
        campoNombre.setEditable(true);
        campoApellidoP.setEditable(true);
        campoApellidoM.setEditable(true);
        campoApellidoM.setEditable(true);
        campoCarrera.setEditable(true);
        campoCorreo.setEditable(true);
        
    }
    public void cargarDatos(){
        campoNombre.setText(this.estudiante.getNombre());
        campoApellidoP.setText(this.estudiante.getApellidoPaterno());
        campoApellidoM.setText(this.estudiante.getApellidoMaterno());
        campoCarrera.setText(this.estudiante.getCarrera());
        campoCorreo.setText(this.estudiante.getCorreo());  
    }
    
    public void obtenerDatos(){
        obtenerHobbys();
        this.estudiante.setHobbies(listaHobbys);
        this.estudiante.setNombre(campoNombre.getText());
        this.estudiante.setApellidoPaterno(campoApellidoP.getText());
        this.estudiante.setApellidoMaterno(campoApellidoM.getText());
        this.estudiante.setCorreo(campoCorreo.getText());
        this.estudiante.setCarrera(campoCarrera.getText());
        control.ActualizarEstudiante(this.estudiante);
    }
    
   
    private void obtenerHobbys(){
        listaHobbys = estudiante.getHobbies();
        if (boxBaile.isSelected()) 
            listaHobbys.add("Baile");
        if (boxCocina.isSelected()) 
            listaHobbys.add("Cocicna");
        if (boxDeportes.isSelected()) 
            listaHobbys.add("Deportes");
        if (boxFototgrafia.isSelected()) 
            listaHobbys.add("Fotografia");
        if (boxLibros.isSelected()) 
            listaHobbys.add("Libros");
        if (boxMusica.isSelected()) listaHobbys.add("Musica");
        if (boxPeliculas.isSelected()) 
            listaHobbys.add("Peliculas");
        if (boxTecnologia.isSelected()) 
            listaHobbys.add("Tecnologia");
        if (boxViajes.isSelected()) listaHobbys.add("Viajes");
        
    }
}
