/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Aplicacion.Control;

/**
 *
 * @author HP
 */
public class PerfilUsuario extends javax.swing.JPanel {
private Control control;
    /**
     * Creates new form PerfilUsuario
     */
    public PerfilUsuario(Control control) {
        this.control = control;
        initComponents();
        iniciarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnHome = new javax.swing.JButton();
        BtnPublicaciones = new javax.swing.JButton();
        labelNombreUsuario = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        BtnEditarPerfil = new javax.swing.JButton();
        labelApellidoP = new javax.swing.JLabel();
        labelApellidoM = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();
        labelHobbys = new javax.swing.JLabel();
        campoCarrera = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        campoHobbys = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        BtnConfirmar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(660, 521));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnHome.setText("Home");
        BtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHomeMouseClicked(evt);
            }
        });
        add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        BtnPublicaciones.setText("Publicaciones");
        add(BtnPublicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 110, 30));

        labelNombreUsuario.setText("NombreUsuario");
        add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelNombre.setText("Nombre");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        BtnEditarPerfil.setText("Editar perfil");
        BtnEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarPerfilMouseClicked(evt);
            }
        });
        add(BtnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 110, 30));

        labelApellidoP.setText("Apellido Paterno");
        add(labelApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        labelApellidoM.setText("Apellido Materno");
        add(labelApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labelCorreo.setText("Correo");
        add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        labelCarrera.setText("Carrera");
        add(labelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        labelHobbys.setText("Hobbys");
        add(labelHobbys, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        add(campoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 220, 30));
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 230, 30));
        add(campoApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 30));
        add(campoHobbys, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 230, 30));
        add(campoApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 220, 30));
        add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 220, 30));

        BtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarPerfilMouseClicked
        // TODO add your handling code here:
       modoEditar();
    }//GEN-LAST:event_BtnEditarPerfilMouseClicked

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
        iniciarPanel();
        //logica para confirmar los cambios en el usuario, falta armar DTO
        
    }//GEN-LAST:event_BtnConfirmarMouseClicked

    private void BtnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMouseClicked
        // TODO add your handling code here:
        control.MostrarMenuPrincipal();
    }//GEN-LAST:event_BtnHomeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JButton BtnEditarPerfil;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnPublicaciones;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoCarrera;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoHobbys;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel labelApellidoM;
    private javax.swing.JLabel labelApellidoP;
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelHobbys;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreUsuario;
    // End of variables declaration//GEN-END:variables

    private void iniciarPanel(){
        campoNombre.setEditable(false);
        campoApellidoP.setEditable(false);
        campoApellidoM.setEditable(false);
        campoApellidoM.setEditable(false);
        campoCarrera.setEditable(false);
        campoHobbys.setEditable(false);
        campoCorreo.setEditable(false);
        
        BtnConfirmar.setVisible(false);
        
        //falta logica de cargar los datos del usuario control.actualizarUsuario(UsuarioDTO u)
        control.getEstudiante();
        
    }
    
    private void modoEditar(){
        campoNombre.setEditable(true);
        campoApellidoP.setEditable(true);
        campoApellidoM.setEditable(true);
        campoApellidoM.setEditable(true);
        campoCarrera.setEditable(true);
        campoCorreo.setEditable(true);
        campoHobbys.setEditable(true);
        
        BtnConfirmar.setVisible(true);
        
    }
    
    public void obtenerDatos(){
        
    }
}
