/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Perfil;

import Aplicacion.Control;
import DTOs.EstudianteDTO;
import DTOs.LikeDTO;
import DTOs.PostDTO;
import Vistas.Post.PanelPost;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.time.Instant;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JScrollPane;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class PanelEstudiante extends javax.swing.JPanel {
private Control control;
private EstudianteDTO estudiante;
private LikeDTO like;

    /**
     * Creates new form PanelEstudiante
     */
    public PanelEstudiante(Control control, EstudianteDTO estudiante) {
        this.control = control;
        this.estudiante = estudiante;
        this.like = new LikeDTO();
        initComponents();
        cargarFeed();
        scrollFeed();
        valoresDefault();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFeed = new javax.swing.JScrollPane();
        barra = new javax.swing.JScrollBar();
        btnHome = new javax.swing.JButton();
        btnLike = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        btnDisLike = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(664, 550));
        setMinimumSize(new java.awt.Dimension(664, 550));
        setPreferredSize(new java.awt.Dimension(664, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFeed.setMaximumSize(new java.awt.Dimension(480, 390));
        panelFeed.setPreferredSize(new java.awt.Dimension(480, 390));

        barra.setPreferredSize(new java.awt.Dimension(540, 450));
        panelFeed.setViewportView(barra);

        add(panelFeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 460, 370));

        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        btnLike.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\corazon.png")); // NOI18N
        btnLike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLikeMouseClicked(evt);
            }
        });
        add(btnLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 50, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("nombre estudinte");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelContenido.setMaximumSize(new java.awt.Dimension(540, 32767));
        panelContenido.setMinimumSize(new java.awt.Dimension(540, 450));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 460, 370));

        btnDisLike.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\corazon (1).png")); // NOI18N
        btnDisLike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisLikeMouseClicked(evt);
            }
        });
        add(btnDisLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnLikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLikeMouseClicked
        // TODO add your handling code here:
        crearLike();
        btnLike.setEnabled(false);
        btnLike.setVisible(false);
        btnDisLike.setVisible(true);
        btnDisLike.setEnabled(true);
    }//GEN-LAST:event_btnLikeMouseClicked

    private void btnDisLikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisLikeMouseClicked
        // TODO add your handling code here:
        btnLike.setEnabled(true);
        btnLike.setVisible(true);
        btnDisLike.setVisible(false);
        btnDisLike.setEnabled(false);
        eliminarLike();
    }//GEN-LAST:event_btnDisLikeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar barra;
    private javax.swing.JButton btnDisLike;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLike;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JScrollPane panelFeed;
    // End of variables declaration//GEN-END:variables


    public void crearLike(){
        like.setEstudianteDestino(control.getEstudianteBuscado());
        like.setEstudianteOrigen(control.getEstudiante());
        like.setFechaHora(Instant.now());
        System.out.println("Like antes de registrar:  " + like.toString());
        control.registrarLike(like);
        
        
        
    }
    public void valoresDefault(){
        btnDisLike.setVisible(false);
        btnDisLike.setEnabled(false);
    }
    
    public void eliminarLike(){
        
        control.eliminarLike(like);
        
    }
    public void cargarFeed(){
        panelContenido.setLayout(new BoxLayout(panelContenido, BoxLayout.Y_AXIS));
        panelContenido.removeAll();
        panelContenido.setPreferredSize(new Dimension(540, control.cargarPostEstudiante(this.estudiante).size()*(450+10)));
        for(PostDTO post: control.cargarPostEstudiante(this.estudiante)){
            System.out.println(post.toString());
            PanelPost publicacion = new PanelPost(control, post);   

            panelContenido.add(publicacion);         
            panelContenido.add(Box.createVerticalStrut(10));
        }
            panelContenido.revalidate();
            panelContenido.repaint();
            panelFeed.setViewportView(panelContenido);
            panelFeed.revalidate();
            panelFeed.repaint();
    }
 
  public void scrollFeed(){
        panelFeed.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        panelFeed.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        barra = panelFeed.getVerticalScrollBar();        
        panelFeed.addMouseWheelListener((new MouseWheelListener() {
        private boolean scroll = false;

            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                e.consume();
                if(scroll || panelContenido.getComponentCount() == 0)return;
                scroll = true;
                
                panelContenido.revalidate();
                Component post1 =  panelContenido.getComponent(0);
                int alturaPost = post1.getPreferredSize().height +10;
                int direccion = e.getWheelRotation();
                int posicionActual = barra.getValue();
                int posicionDeseada = posicionActual + direccion* alturaPost;
 
                final int nuevaPosicion = Math.max(0, Math.min(posicionDeseada, barra.getMaximum() - barra.getVisibleAmount()));
                Timer timer = new Timer(5, null);
                timer.addActionListener(ae ->{
                    int valorA = barra.getValue();
                    int velocidad = 10;
                    if(direccion> 0){
                        int siguiente = Math.min(valorA + velocidad, nuevaPosicion);
                        barra.setValue(siguiente);
                        if(siguiente >= nuevaPosicion)
                        {
                            timer.stop();
                            scroll = false;
                        }
                    }else{
                        int siguiente = Math.max(valorA- velocidad, nuevaPosicion);
                        barra.setValue(siguiente);
                        if(siguiente<= nuevaPosicion) {
                            timer.stop();
                            scroll = false;
                        }
                    }
                });
                timer.start();
             }
         }));  
     }

}
