/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Perfil;

import Aplicacion.Control;
import DTOs.EstudianteDTO;
import entidades.Hobby;
import java.util.List;
import java.lang.reflect.Array;

/**
 *
 * @author HP
 */
public class PerfilUsuario extends javax.swing.JPanel {
private Control control;
    /**
     * Creates new form PerfilUsuario
     */
    public PerfilUsuario(Control control) {
        this.control = control;
        initComponents();
        iniciarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnHome = new javax.swing.JButton();
        BtnPublicaciones = new javax.swing.JButton();
        labelNombreUsuario = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        BtnEditarPerfil = new javax.swing.JButton();
        labelApellidoP = new javax.swing.JLabel();
        labelApellidoM = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();
        labelHobbys = new javax.swing.JLabel();
        campoCarrera = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listHobbys = new javax.swing.JList<>();
        BtnLogOut = new javax.swing.JButton();
        btnCrearPost = new javax.swing.JButton();
        btnBuscr = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(660, 521));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\hogar.png")); // NOI18N
        BtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHomeMouseClicked(evt);
            }
        });
        add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 60, 50));

        BtnPublicaciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\mispost.png")); // NOI18N
        BtnPublicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPublicacionesMouseClicked(evt);
            }
        });
        add(BtnPublicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 80, 50));

        labelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombreUsuario.setText("NombreUsuario");
        add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, -1));

        labelNombre.setText("Nombre");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        BtnEditarPerfil.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\editar-perfil.png")); // NOI18N
        BtnEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarPerfilMouseClicked(evt);
            }
        });
        add(BtnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 80, 50));

        labelApellidoP.setText("Apellido Paterno");
        add(labelApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        labelApellidoM.setText("Apellido Materno");
        add(labelApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labelCorreo.setText("Correo");
        add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        labelCarrera.setText("Carrera");
        add(labelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        labelHobbys.setText("Hobbys");
        add(labelHobbys, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        add(campoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 220, 30));
        add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 230, 30));
        add(campoApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 230, 30));
        add(campoApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 220, 30));
        add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 220, 30));

        listHobbys.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listHobbys);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 180, 160));

        BtnLogOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\cerrar-sesion.png")); // NOI18N
        BtnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogOutMouseClicked(evt);
            }
        });
        add(BtnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 60, 50));

        btnCrearPost.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\nuevopost.png")); // NOI18N
        btnCrearPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPostMouseClicked(evt);
            }
        });
        add(btnCrearPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 80, 50));

        btnBuscr.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\ITSON\\Clases5Semestre\\BDA2.0\\Java´s\\Repositorio Proyecto02\\Sistema-match\\Imagenes\\vaso.png")); // NOI18N
        btnBuscr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscrMouseClicked(evt);
            }
        });
        add(btnBuscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 60, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarPerfilMouseClicked
        // TODO add your handling code here:
       control.mostrarEditarPerfil();
    }//GEN-LAST:event_BtnEditarPerfilMouseClicked

    private void BtnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuPrincipal();
    }//GEN-LAST:event_BtnHomeMouseClicked

    private void BtnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogOutMouseClicked
        // TODO add your handling code here:
        control.mostrarLogIn();
    }//GEN-LAST:event_BtnLogOutMouseClicked

    private void BtnPublicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPublicacionesMouseClicked
        // TODO add your handling code here:
        control.mostrarPublicacionesEstudiante();
        
    }//GEN-LAST:event_BtnPublicacionesMouseClicked

    private void btnCrearPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPostMouseClicked
        // TODO add your handling code here:
        control.mostrarCrearPublicaciones();
    }//GEN-LAST:event_btnCrearPostMouseClicked

    private void btnBuscrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscrMouseClicked
        // TODO add your handling code here:
        control.mostrarBuscarEstudiante();
    }//GEN-LAST:event_btnBuscrMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditarPerfil;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnPublicaciones;
    private javax.swing.JButton btnBuscr;
    private javax.swing.JButton btnCrearPost;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoCarrera;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApellidoM;
    private javax.swing.JLabel labelApellidoP;
    private javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelHobbys;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JList<String> listHobbys;
    // End of variables declaration//GEN-END:variables

    private void iniciarPanel(){
        campoNombre.setEditable(false);
        campoApellidoP.setEditable(false);
        campoApellidoM.setEditable(false);
        campoApellidoM.setEditable(false);
        campoCarrera.setEditable(false);
        
        campoCorreo.setEditable(false);
        cargarDatos();  
    }

//    private void modoEditar(){
//        control.mostrarEditarPerfil();
//        listHobbys.setVisible(false);
//        campoNombre.setEditable(true);
//        campoApellidoP.setEditable(true);
//        campoApellidoM.setEditable(true);
//        campoApellidoM.setEditable(true);
//        campoCarrera.setEditable(true);
//        campoCorreo.setEditable(true);
//        
//        
//        BtnConfirmar.setVisible(true);
//        
//    }
    
    public void cargarDatos(){
        EstudianteDTO estudianteDto = control.getEstudiante();
        System.out.println("estudiante al abrir panel PerfilUsuario:  " + estudianteDto.toString());
        campoNombre.setText(estudianteDto.getNombre());
        campoApellidoP.setText(estudianteDto.getApellidoPaterno());
        campoApellidoM.setText(estudianteDto.getApellidoMaterno());
        campoCarrera.setText(estudianteDto.getCarrera());
        campoCorreo.setText(estudianteDto.getCorreo());
        
        List<String> hobbys = control.getEstudiante().getHobbies();
        if (hobbys != null && !hobbys.isEmpty()) {
            listHobbys.setListData(hobbys.toArray(new String[0]));
        }else {
            listHobbys.setListData(
                    new String[]{"Sin hobbies registrados"}
                    );
            }
        }
        
    }
